enum AreaAtuacao {
    EDUCACAO = 'Educação',
    SAUDE = 'Saúde',
    AMBIENTE = 'Meio Ambiente',
    TECNOLOGIA = 'Tecnologia',
    CULTURA = 'Cultura',
    DIREITOS_HUMANOS = 'Direitos Humanos',
    FOME = 'Combate à Fome',
    POBREZA = 'Combate à Pobreza',
    ANIMAL = 'Proteção Animal',
    CRIANCA = 'Proteção à Criança',
    MULHER = 'Direitos das Mulheres',
    IGUALDADE = 'Igualdade de Gênero',
    IDOSO = 'Apoio ao Idoso',
    LGBTQIA = 'Direitos LGBTQIA+',
    REFUGIADOS = 'Apoio a Refugiados',
    EDUCACAO_INFANTIL = 'Educação Infantil',
    EMPREGO = 'Geração de Emprego',
    VOLUNTARIADO = 'Promoção do Voluntariado',
    ESPORTES = 'Esportes',
    ARTE = 'Arte e Cultura',
    FAMILIA = 'Apoio à Família',
    SAUDE_MENTAL = 'Saúde Mental',
    REABILITACAO = 'Reabilitação Social',
    JUSTICA_SOCIAL = 'Justiça Social',
    SEGURANCA_ALIMENTAR = 'Segurança Alimentar',
    DESENVOLVIMENTO_SUSTENTAVEL = 'Desenvolvimento Sustentável',
    INFRAESTRUTURA = 'Infraestrutura Comunitária',
    EMPODERAMENTO = 'Empoderamento de Comunidades',
    TECNOLOGIA_SOCIAL = 'Tecnologia Social'
  }
  