enum AreaAtuacao {
  EDUCACAO = 'EDUCACAO',
  SAUDE = 'SAUDE',
  AMBIENTE = 'AMBIENTE',
  TECNOLOGIA = 'TECNOLOGIA',
  CULTURA = 'CULTURA',
  DIREITOS_HUMANOS = 'DIREITOS_HUMANOS',
  FOME = 'FOME',
  POBREZA = 'POBREZA',
  ANIMAL = 'ANIMAL',
  CRIANCA = 'CRIANCA',
  MULHER = 'MULHER',
  IGUALDADE = 'IGUALDADE',
  IDOSO = 'IDOSO',
  LGBTQIA = 'LGBTQIA',
  REFUGIADOS = 'REFUGIADOS',
  EDUCACAO_INFANTIL = 'EDUCACAO_INFANTIL',
  EMPREGO = 'EMPREGO',
  VOLUNTARIADO = 'VOLUNTARIADO',
  ESPORTES = 'ESPORTES',
  ARTE = 'ARTE',
  FAMILIA = 'FAMILIA',
  SAUDE_MENTAL = 'SAUDE_MENTAL',
  REABILITACAO = 'REABILITACAO',
  JUSTICA_SOCIAL = 'JUSTICA_SOCIAL',
  SEGURANCA_ALIMENTAR = 'SEGURANCA_ALIMENTAR',
  DESENVOLVIMENTO_SUSTENTAVEL = 'DESENVOLVIMENTO_SUSTENTAVEL',
  INFRAESTRUTURA = 'INFRAESTRUTURA',
  EMPODERAMENTO = 'EMPODERAMENTO',
  TECNOLOGIA_SOCIAL = 'TECNOLOGIA_SOCIAL'
}

export default AreaAtuacao;

