const Erros = {
  NOME_VAZIO: "NOME_VAZIO",
  NOME_NULO: "NOME_NULO",
  SENHA_INVALIDA: "SENHA_INVALIDA",
  ID_INVALIDO: "ID_INVALIDO",
  EMAIL_INVALIDO: "EMAIL_INVALIDO",
  IMAGEM_INVALIDA: "IMAGEM_INVALIDA",
  TIPO_INVALIDO: "TIPO_INVALIDO",
  ARRAY_INVALIDO: "ARRAY_INVALIDO",
};

export default Erros;
