const Erros = {
  NOME_VAZIO: "NOME_VAZIO",
  NOME_NULO: "NOME_NULO",
  SENHA_INVALIDA: "SENHA_INVALIDA",
  ID_INVALIDO: "ID_INVALIDO",
  EMAIL_INVALIDO: "EMAIL_INVALIDO",
  IMAGEM_INVALIDA: "IMAGEM_INVALIDA",
  TIPO_INVALIDO: "TIPO_INVALIDO",
  CNPJ_INVALIDO: "CNPJ_INVALIDO",
  ARRAY_INVALIDO: "ARRAY_INVALIDO",
  INTERESSES_INVALIDOS: "INTERESSES_INVALIDOS",
  HABILIDADES_INVALIDAS: "HABILIDADES_INVALIDAS",
  MISSAO_VAZIA : "MISSAO_VAZIA",
  DESCRICAO_VAZIA:"DESCRICAO_VAZIA",
  VISAO_VAZIA: "VISAO_VAZIA",
  ENDERECO_VAZIO:"ENDERECO_VAZIO"
  
};

export default Erros;
